
const products = [
  {
    id: 1,
    category: 'Coffee',
    name: 'Irish coffee',
    description: 'Fragrant black coffee with Jameson Irish whiskey and whipped milk',
    cost: `7.00`,
    currency: '$',
    favorite: false,
    src: '../img/assets/photos/irishCoffee.jpg',
  },
  {
    id: 2,
    category: 'Coffee', 
    name: 'Kahlua coffee',
    description: 'Classic coffee with milk and Kahlua liqueur under a cap of frothed milk',
    cost: `7.00`,
    currency: '$',
    favorite: false,
    src: '../img/assets/photos/kahluaCoffee.jpg',
  },
  {
    id: 3,
    category: 'Coffee',
    name: 'Honey raf',
    description: 'Espresso with frothed milk, cream and aromatic honey',
    cost: `5.50`,
    currency: '$',
    favorite: false,
    src: '../img/assets/photos/honeyRaf.jpg',
  },
  {
    id: 4,
    category: 'Coffee',
    name: 'Ice cappuccino',
    description: 'Cappuccino with soft thick foam in summer version with ice',
    cost: `5.00`,
    currency: '$',
    favorite: false,
    src: '../img/assets/photos/iceCappuccino.jpg',
  },
  {
    id: 5,
    category: 'Coffee',
    name: 'Espresso',
    description: 'Classic black coffee',
    cost: `4.50`,
    currency: '$',
    favorite: false,
    src: '../img/assets/photos/espessoCoffee.jpg',
  },
  {
    id: 6,
    category: 'Coffee',
    name: 'Latte',
    description: 'Espresso coffee with the addition of steamed milk and dense milk foam',
    cost: `5.50`,
    currency: '$',
    favorite: false,
    src: '../img/assets/photos/latteCoffee.jpg',
  },
  {
    id: 7,
    category: 'Coffee',
    name: 'Latte macchiato',
    description: 'Espresso with frothed milk and chocolate',
    cost: `5.50`,
    currency: '$',
    favorite: false,
    src: '../img/assets/photos/latteMacchiatoCoffee.jpg',
  },
  {
    id: 8,
    category: 'Coffee',
    name: 'Coffee with cognac',
    description: 'Fragrant black coffee with cognac and whipped cream',
    cost: `6.50`,
    currency: '$',
    favorite: false,
    src: '../img/assets/photos/coffeeWithCognac.jpg',
  },
  {
    id: 9,
    category: 'Coffee',
    name: 'S’mores Frappuccino',
    description: 'This new drink takes an espresso and mixes it with brown sugar and cinnamon before being topped with oat milk.',
    cost: `5.50`,
    currency: '$',
    favorite: true,
    src: '../img/assets/photos/moresFrappuccino.png',
  },

  
  {
    id: 10,
    category: 'Coffee',
    name: 'Caramel Macchiato',
    description: 'Fragrant adnd unique classic espresso with rich caramel-peanut syrup, with cream under whipped thick foam.',
    cost: `5.50`,
    currency: '$',
    favorite: true,
    src: '../img/assets/photos/caramelMacchiato.png',
  },

  {
    id: 11,
    category: 'Coffee',
    name: 'Ice Coffee',
    description: 'A popular summer drink that tones and invigorates. Prepared from coffee, milk and ice.',
    cost: `4.50`,
    currency: '$',
    favorite: true,
    src: '../img/assets/photos/iceCoffee.png',
  },
];
